services:
  bolt-ai-dev:
    image: bolt-ai:dev
    build:
      target: bolt-ai-dev
    environment:
      - NODE_ENV=dev
      - VITE_HMR_PROTOCOL=ws
      - VITE_HMR_HOST=localhost
      - VITE_HMR_PORT=5173
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true  
      - PORT=5173
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - VITE_LOG_LEVEL=${VITE_LOG_LEVEL:-debug}
      - RUNNING_IN_DOCKER=true
    extra_hosts:
      - "host.docker.internal:host-gateway"      
    volumes:
      - type: bind
        source: .
        target: /app
        consistency: cached
      - /app/node_modules
    ports:
      - "5173:5173"  
    command: pnpm run dev --host 0.0.0.0
    profiles: ["dev", "default"]  
